import type {
  User,
  Subject,
  Lesson,
  MockExam,
  SBPProject,
  OfflineModule,
} from "./types";

export const mockUser: User = {
  id: "u_001",
  phone: "+263771234567",
  name: "Tatenda",
  level: "O-Level",
  avatar: "T",
  xp: 2450,
  streak: 7,
  lastActiveDate: "2026-04-07",
  premium: false,
  deviceProfile: {
    ramGB: 3,
    batteryPct: 65,
    lowEnd: false,
    darkMode: true,
  },
  createdAt: "2026-01-15",
};

export const mockSubjects: Subject[] = [
  {
    id: "math-o",
    name: "Mathematics",
    level: "O-Level",
    icon: "📐",
    color: "#22c55e",
    progress: 0.42,
    nodes: [
      {
        id: "n1",
        title: "Number Systems",
        description: "Integers, rationals, and real numbers",
        status: "completed",
        xpReward: 100,
        stars: 3,
        order: 1,
        lessonCount: 5,
        completedLessons: 5,
      },
      {
        id: "n2",
        title: "Algebraic Expressions",
        description: "Simplification and factorisation",
        status: "completed",
        xpReward: 150,
        stars: 2,
        order: 2,
        lessonCount: 8,
        completedLessons: 8,
      },
      {
        id: "n3",
        title: "Quadratic Equations",
        description: "Solving quadratics by factoring and formula",
        status: "active",
        xpReward: 200,
        stars: 0,
        order: 3,
        lessonCount: 6,
        completedLessons: 3,
      },
      {
        id: "n4",
        title: "Simultaneous Equations",
        description: "Linear and non-linear pairs",
        status: "locked",
        xpReward: 200,
        stars: 0,
        order: 4,
        lessonCount: 5,
        completedLessons: 0,
      },
      {
        id: "n5",
        title: "Geometry & Mensuration",
        description: "Areas, volumes, and circle theorems",
        status: "locked",
        xpReward: 250,
        stars: 0,
        order: 5,
        lessonCount: 10,
        completedLessons: 0,
      },
      {
        id: "n6",
        title: "Trigonometry",
        description: "Sine, cosine, tangent and applications",
        status: "locked",
        xpReward: 300,
        stars: 0,
        order: 6,
        lessonCount: 8,
        completedLessons: 0,
      },
      {
        id: "n7",
        title: "Statistics & Probability",
        description: "Data handling and probability theory",
        status: "locked",
        xpReward: 250,
        stars: 0,
        order: 7,
        lessonCount: 7,
        completedLessons: 0,
      },
    ],
  },
  {
    id: "phys-o",
    name: "Physics",
    level: "O-Level",
    icon: "⚡",
    color: "#3b82f6",
    progress: 0.15,
    nodes: [
      {
        id: "p1",
        title: "Measurement",
        description: "SI units and scientific notation",
        status: "completed",
        xpReward: 100,
        stars: 3,
        order: 1,
        lessonCount: 4,
        completedLessons: 4,
      },
      {
        id: "p2",
        title: "Mechanics",
        description: "Forces, motion, and energy",
        status: "active",
        xpReward: 200,
        stars: 0,
        order: 2,
        lessonCount: 10,
        completedLessons: 2,
      },
      {
        id: "p3",
        title: "Waves",
        description: "Sound, light, and electromagnetic spectrum",
        status: "locked",
        xpReward: 200,
        stars: 0,
        order: 3,
        lessonCount: 8,
        completedLessons: 0,
      },
    ],
  },
  {
    id: "hist-o",
    name: "History",
    level: "O-Level",
    icon: "📜",
    color: "#f59e0b",
    progress: 0.3,
    nodes: [
      {
        id: "h1",
        title: "Pre-Colonial Zimbabwe",
        description: "Great Zimbabwe, Mutapa, and Rozvi states",
        status: "completed",
        xpReward: 150,
        stars: 2,
        order: 1,
        lessonCount: 6,
        completedLessons: 6,
      },
      {
        id: "h2",
        title: "Colonial Era",
        description: "BSAC, settler colonialism, and resistance",
        status: "active",
        xpReward: 200,
        stars: 0,
        order: 2,
        lessonCount: 8,
        completedLessons: 3,
      },
    ],
  },
  {
    id: "chem-o",
    name: "Chemistry",
    level: "O-Level",
    icon: "🧪",
    color: "#a855f7",
    progress: 0.0,
    nodes: [
      {
        id: "c1",
        title: "Atomic Structure",
        description: "Protons, neutrons, electrons and isotopes",
        status: "active",
        xpReward: 100,
        stars: 0,
        order: 1,
        lessonCount: 5,
        completedLessons: 0,
      },
    ],
  },
];

export const mockLessons: Record<string, Lesson[]> = {
  n3: [
    {
      id: "l_q3_01",
      nodeId: "n3",
      title: "Solving by Factoring",
      questionText: "Solve for x:",
      questionLatex: "x^2 + 5x + 6 = 0",
      options: [
        { text: "x = -2 or x = -3", latex: "x = -2 \\text{ or } x = -3" },
        { text: "x = 2 or x = 3", latex: "x = 2 \\text{ or } x = 3" },
        { text: "x = -1 or x = -6", latex: "x = -1 \\text{ or } x = -6" },
        { text: "x = 1 or x = 6", latex: "x = 1 \\text{ or } x = 6" },
      ],
      correctIndex: 0,
      explanation:
        "Factor the quadratic: (x + 2)(x + 3) = 0. Setting each factor to zero gives x = -2 or x = -3.",
      xpReward: 25,
    },
    {
      id: "l_q3_02",
      nodeId: "n3",
      title: "Quadratic Formula",
      questionText: "Use the quadratic formula to solve:",
      questionLatex: "2x^2 - 7x + 3 = 0",
      options: [
        { text: "x = 3 or x = 1/2", latex: "x = 3 \\text{ or } x = \\frac{1}{2}" },
        { text: "x = -3 or x = -1/2", latex: "x = -3 \\text{ or } x = -\\frac{1}{2}" },
        { text: "x = 7 or x = 3", latex: "x = 7 \\text{ or } x = 3" },
        { text: "x = 1 or x = 3/2", latex: "x = 1 \\text{ or } x = \\frac{3}{2}" },
      ],
      correctIndex: 0,
      explanation:
        "Using the quadratic formula x = (-b ± √(b²-4ac)) / 2a with a=2, b=-7, c=3 gives x = (7 ± 5) / 4, so x = 3 or x = 1/2.",
      xpReward: 30,
    },
    {
      id: "l_q3_03",
      nodeId: "n3",
      title: "Completing the Square",
      questionText: "Express in the form (x + a)² + b:",
      questionLatex: "x^2 + 6x + 2",
      options: [
        { text: "(x + 3)² - 7", latex: "(x + 3)^2 - 7" },
        { text: "(x + 3)² + 7", latex: "(x + 3)^2 + 7" },
        { text: "(x + 6)² - 34", latex: "(x + 6)^2 - 34" },
        { text: "(x + 2)² - 2", latex: "(x + 2)^2 - 2" },
      ],
      correctIndex: 0,
      explanation:
        "Half of 6 is 3, so (x + 3)² = x² + 6x + 9. Then x² + 6x + 2 = (x + 3)² - 9 + 2 = (x + 3)² - 7.",
      xpReward: 30,
    },
  ],
  p2: [
    {
      id: "l_p2_01",
      nodeId: "p2",
      title: "Newton's Second Law",
      questionText: "A 5 kg object accelerates at 3 m/s². What is the net force?",
      options: [
        { text: "15 N" },
        { text: "8 N" },
        { text: "1.67 N" },
        { text: "150 N" },
      ],
      correctIndex: 0,
      explanation: "F = ma = 5 × 3 = 15 N.",
      xpReward: 20,
    },
    {
      id: "l_p2_02",
      nodeId: "p2",
      title: "Kinetic Energy",
      questionText: "Calculate the kinetic energy:",
      questionLatex: "E_k = \\frac{1}{2}mv^2, \\quad m = 4\\text{ kg}, \\quad v = 6\\text{ m/s}",
      options: [
        { text: "72 J" },
        { text: "12 J" },
        { text: "48 J" },
        { text: "144 J" },
      ],
      correctIndex: 0,
      explanation: "Eₖ = ½mv² = ½ × 4 × 36 = 72 J.",
      xpReward: 25,
    },
  ],
  h2: [
    {
      id: "l_h2_01",
      nodeId: "h2",
      title: "The BSAC",
      questionText: "In what year was the British South Africa Company (BSAC) granted a royal charter?",
      options: [
        { text: "1889" },
        { text: "1890" },
        { text: "1895" },
        { text: "1880" },
      ],
      correctIndex: 0,
      explanation: "The BSAC was granted a royal charter by Queen Victoria in October 1889.",
      xpReward: 20,
    },
    {
      id: "l_h2_02",
      nodeId: "h2",
      title: "The Pioneer Column",
      questionText: "What was the Pioneer Column?",
      options: [
        { text: "A group of settlers who occupied Mashonaland in 1890" },
        { text: "A military regiment in the Anglo-Boer War" },
        { text: "A newspaper founded by Cecil Rhodes" },
        { text: "A trade route through Matabeleland" },
      ],
      correctIndex: 0,
      explanation: "The Pioneer Column was a group of settlers recruited by the BSAC who marched into Mashonaland and founded Fort Salisbury (Harare) in September 1890.",
      xpReward: 20,
    },
  ],
  c1: [
    {
      id: "l_c1_01",
      nodeId: "c1",
      title: "Atomic Number",
      questionText: "What does the atomic number of an element represent?",
      options: [
        { text: "The number of protons in the nucleus" },
        { text: "The total number of protons and neutrons" },
        { text: "The number of electrons in the outer shell" },
        { text: "The mass of the atom in grams" },
      ],
      correctIndex: 0,
      explanation: "The atomic number (Z) is the number of protons in the nucleus. It defines the element.",
      xpReward: 15,
    },
    {
      id: "l_c1_02",
      nodeId: "c1",
      title: "Isotopes",
      questionText: "Isotopes of an element have the same number of _____ but different numbers of _____.",
      options: [
        { text: "protons; neutrons" },
        { text: "neutrons; protons" },
        { text: "electrons; protons" },
        { text: "protons; electrons" },
      ],
      correctIndex: 0,
      explanation: "Isotopes share the same atomic number (protons) but have different mass numbers due to different numbers of neutrons.",
      xpReward: 15,
    },
  ],
};

export const mockExam: MockExam = {
  id: "exam_math_2024_p1",
  subjectId: "math-o",
  title: "Mathematics Paper 1",
  year: 2024,
  paper: 1,
  durationMinutes: 150,
  questions: [
    {
      id: "eq1",
      questionNumber: 1,
      text: "Evaluate 3.42 × 10⁻³ + 1.58 × 10⁻³, giving your answer in standard form.",
      options: [
        "5.0 × 10⁻³",
        "5.0 × 10⁻²",
        "0.5 × 10⁻²",
        "50 × 10⁻⁴",
      ],
      correctIndex: 0,
      marks: 2,
    },
    {
      id: "eq2",
      questionNumber: 2,
      text: "Simplify the expression:",
      latex: "\\frac{2x^2 - 8}{x - 2}",
      options: ["2(x + 2)", "2x + 4", "2(x - 2)", "x² - 4"],
      correctIndex: 0,
      marks: 3,
    },
    {
      id: "eq3",
      questionNumber: 3,
      text: "A triangle has vertices at A(1,2), B(5,2), and C(3,6). Find the area of triangle ABC.",
      options: ["8 sq units", "10 sq units", "12 sq units", "6 sq units"],
      correctIndex: 0,
      marks: 4,
      diagramSvg: `<svg viewBox="0 0 200 160" xmlns="http://www.w3.org/2000/svg">
        <polygon points="30,120 170,120 100,20" fill="none" stroke="currentColor" stroke-width="2"/>
        <text x="20" y="135" fill="currentColor" font-size="12">A(1,2)</text>
        <text x="150" y="135" fill="currentColor" font-size="12">B(5,2)</text>
        <text x="85" y="15" fill="currentColor" font-size="12">C(3,6)</text>
      </svg>`,
    },
    {
      id: "eq4",
      questionNumber: 4,
      text: "The bearing of town B from town A is 065°. What is the bearing of town A from town B?",
      options: ["245°", "295°", "115°", "155°"],
      correctIndex: 0,
      marks: 2,
    },
    {
      id: "eq5",
      questionNumber: 5,
      text: "If the exchange rate is 1 USD = 6500 ZWL, how much in USD is 325 000 ZWL?",
      options: ["$50", "$45", "$55", "$40"],
      correctIndex: 0,
      marks: 2,
    },
  ],
};

export const mockSBPProjects: SBPProject[] = [
  {
    id: "sbp_001",
    title: "Soil pH and Crop Yield Analysis",
    subject: "Agriculture",
    stage: "data-collection",
    progress: 0.4,
    dueDate: "2026-09-15",
    tasks: [
      {
        id: "t1",
        title: "Define research question",
        stage: "ideation",
        completed: true,
      },
      {
        id: "t2",
        title: "Literature review on soil pH",
        stage: "ideation",
        completed: true,
      },
      {
        id: "t3",
        title: "Write hypothesis",
        stage: "drafting",
        completed: true,
      },
      {
        id: "t4",
        title: "Design data collection methodology",
        stage: "drafting",
        completed: true,
      },
      {
        id: "t5",
        title: "Collect soil samples (5 sites)",
        stage: "data-collection",
        completed: false,
        notes: "3 of 5 sites sampled",
      },
      {
        id: "t6",
        title: "Record crop growth measurements",
        stage: "data-collection",
        completed: false,
      },
      {
        id: "t7",
        title: "Analyse data and create graphs",
        stage: "data-collection",
        completed: false,
      },
      {
        id: "t8",
        title: "Write final report",
        stage: "final-submission",
        completed: false,
      },
      {
        id: "t9",
        title: "Peer review and edit",
        stage: "final-submission",
        completed: false,
      },
      {
        id: "t10",
        title: "Submit portfolio",
        stage: "final-submission",
        completed: false,
      },
    ],
  },
];

export const mockOfflineModules: OfflineModule[] = [
  { id: "om1", name: "O-Level Math — Module 1: Numbers & Algebra", sizeMB: 1.2, downloaded: true },
  { id: "om2", name: "O-Level Math — Module 2: Geometry", sizeMB: 1.8, downloaded: true },
  { id: "om3", name: "O-Level Math — Module 3: Trigonometry", sizeMB: 1.5, downloaded: false },
  { id: "om4", name: "O-Level Physics — Module 1: Measurement", sizeMB: 0.9, downloaded: true },
  { id: "om5", name: "O-Level Physics — Module 2: Mechanics", sizeMB: 2.1, downloaded: false },
  { id: "om6", name: "O-Level History — Full Module", sizeMB: 3.2, downloaded: false },
  { id: "om7", name: "O-Level Chemistry — Module 1: Atomic Structure", sizeMB: 1.1, downloaded: false },
  { id: "om8", name: "Mock Exams Pack 2024", sizeMB: 4.5, downloaded: false },
];
